export const mockStartups = [
  {
    id: 1,
    name: "VoiceCraft AI",
    category: "AI Voice Agents",
    launchDate: "Today",
    pricing: "Freemium ($29/mo)",
    opportunityScore: 92,
    scores: { demand: 9, competition: 4, monetization: 9 },
    aiAnalysis: "High demand in automated customer support. Weak competition for SMBs.",
    description: "Deploy realistic AI voice agents for inbound sales in 5 minutes.",
  },
  {
    id: 2,
    name: "BuildSync",
    category: "Construction AI",
    launchDate: "Yesterday",
    pricing: "Pro ($199/mo)",
    opportunityScore: 88,
    scores: { demand: 8, competition: 2, monetization: 10 },
    aiAnalysis: "Underserved niche. Construction companies are starting to adopt AI for scheduling.",
    description: "AI-powered schedule management for commercial construction projects.",
  },
  {
    id: 3,
    name: "SafeGuard LLM",
    category: "AI Safety",
    launchDate: "2 days ago",
    pricing: "Enterprise",
    opportunityScore: 85,
    scores: { demand: 9, competition: 6, monetization: 8 },
    aiAnalysis: "Growing need for compliance in enterprise AI deployments.",
    description: "Automated red-teaming and compliance checking for enterprise LLMs.",
  },
  {
    id: 4,
    name: "ChatGenie",
    category: "Generic Chatbots",
    launchDate: "Today",
    pricing: "Free",
    opportunityScore: 41,
    scores: { demand: 6, competition: 10, monetization: 3 },
    aiAnalysis: "Highly saturated market. Hard to differentiate without a specific niche.",
    description: "Yet another ChatGPT wrapper for website customer support.",
  },
  {
    id: 5,
    name: "EduMentor",
    category: "AI Education Apps",
    launchDate: "3 days ago",
    pricing: "$9.99/mo",
    opportunityScore: 78,
    scores: { demand: 9, competition: 7, monetization: 6 },
    aiAnalysis: "Strong growth in personalized learning, but B2C churn can be high.",
    description: "Personalized AI tutor that adapts to student learning styles.",
  }
];

export const mockTrends = [
  { category: "AI Voice Agents", growth: 124, status: "rising" },
  { category: "Construction AI", growth: 85, status: "rising" },
  { category: "AI Sales Tools", growth: 62, status: "rising" },
  { category: "NFT Tools", growth: -45, status: "declining" },
  { category: "Generic Chatbots", growth: -20, status: "declining" },
];
